name: Android Build APK

# Workflow ini otomatis jalan saat push ke main atau PR, juga bisa dijalankan manual
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # 3. Berikan izin executable untuk gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      # 5. Upload Debug APK sebagai artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
